<?xml version="1.0"?>
<robot name="rover" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="base_width" value="0.31"/>
    <xacro:property name="base_length" value="0.42"/>
    <xacro:property name="base_height" value="0.184"/>
    <xacro:property name="wheel_radius" value="0.098"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_ygap" value="0.02"/>
    <xacro:property name="wheel_zoff" value="0.125"/>
    <xacro:property name="wheel_xoff" value="0.15"/>
    <xacro:property name="wheel_offset" value="${wheel_radius + wheel_zoff}"/>
    <gazebo>
        <plugin
                filename="ignition-gazebo-sensors-system"
                name="ignition::gazebo::systems::Sensors">
                <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>


    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 -${wheel_offset}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <surface>
                    <friction>
                        <ode>
                            <mu>1</mu>  <!-- Friction coefficient -->
                            <mu2>0.5</mu2> <!-- Secondary friction coefficient -->
                            <slip1>0.0026</slip1>
                            <slip2>0</slip2>
                        </ode>
                    </friction>
                </surface>
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-1e50" upper="1e50" effort="1000" velocity="2.0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

    <xacro:wheel prefix="frontwhl_l" x_reflect="1" y_reflect="1" />
    <xacro:wheel prefix="frontwhl_r" x_reflect="1" y_reflect="-1" />

    <link name="imu_link">
        <visual>
            <geometry>
            <box size="0.1 0.1 0.1"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
            <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="0.1" w="0.1" d="0.1" h="0.1"/>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0.01"/>
    </joint>

    <gazebo reference="imu_link">
        <sensor name="imu_sensor" type="imu">
            <topic>imu</topic>
            <always_on>true</always_on>
            <update_rate>50</update_rate>
            <ignition_frame_id>imu_link</ignition_frame_id>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.004</stddev>  <!-- Increase this if needed -->
            </noise>
        </sensor>
    </gazebo>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${base_length/2} 0 ${base_height/4}" rpy="0 ${pi/9} 0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="0.015 0.130 0.022"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="0.015 0.130 0.022"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.035"/>
            <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"/>

    <gazebo reference="camera_link">
        <sensor name="rgb_camera" type="camera">
            <ignition_frame_id>camera_link_optical</ignition_frame_id>
            <pose>0 0 0 0 0 0</pose>
            <camera>
                <horizontal_fov>1.21126</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>RGB_INT8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <always_on>1</always_on>
            <update_rate>90</update_rate>
            <visualize>false</visualize>
        </sensor>
        <sensor name="depth_camera" type="depth">
            <ignition_frame_id>camera_link_optical</ignition_frame_id>
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <camera>
                <horizontal_fov>1.487021</horizontal_fov>
                <width>1280</width>
                <height>720</height>
                <clip>
                    <near>0.1</near>
                    <far>10</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.100</stddev>
                </noise>
            </camera>
            <always_on>1</always_on>
            <update_rate>90</update_rate>
            <visualize>0</visualize>
        </sensor>
    </gazebo>

    <link name="gps_link"/>

    <joint name="gps_joint" type="fixed">
        <parent link="base_link"/>
        <child link="gps_link"/>
        <origin xyz="0 0.1 0" rpy="0 0 0"/>
    </joint>

    <gazebo reference="gps_link">
        <sensor name="navsat" type="navsat">
            <ignition_frame_id>gps_link</ignition_frame_id>
            <always_on>1</always_on>
            <update_rate>1</update_rate>
            <topic>navsat</topic>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin
            filename="libignition-gazebo-diff-drive-system.so"
            name="ignition::gazebo::systems::DiffDrive">
            <left_joint>frontwhl_l_joint</left_joint>
            <right_joint>frontwhl_r_joint</right_joint>
            <left_joint>drivewhl_l_joint</left_joint>
            <right_joint>drivewhl_r_joint</right_joint>
            <wheel_separation>${base_length}</wheel_separation> 
            <wheel_radius>${wheel_radius}</wheel_radius> 
            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
            <enable_odom_tf>false</enable_odom_tf>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
            <odom_publish_frequency>50</odom_publish_frequency>  
            <max_angular_velocity>0.4</max_angular_velocity>
            <min_angular_velocity>-0.4</min_angular_velocity>
        </plugin>
    </gazebo> 
</robot>
