; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = teensy41



[env]
framework = arduino
upload_port = /dev/ttyACM0
platform = teensy
; Filter out main_old.cpp
src_filter = +<*.cpp> -<main_old.cpp>
; Micro-ROS configuration
board_microros_transport = serial
board_microros_distro = ${sysenv.ROS_DISTRO}
monitor_speed = 921600
monitor_port = /dev/ttyACM0
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    PaulStoffregen/Time
build_flags =
    '-D LOCAL_MAC={ 0xAA, 0xBB, 0xCC, 0xEE, 0xDD, 0xFF }'
    '-D LOCAL_IP={ 192, 168, 1, 101 }'
    '-D AGENT_IP={ 192, 168, 1, 100 }'
    '-D AGENT_PORT=8888'
    '-D WIFI_SSID="wifi_ssid"'
    '-D WIFI_PASSWORD="wifi_password"'

[env:rpipico]
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyACM0
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
board_build.core = earlephilhower
lib_ldf_mode = chain+
#enable serial.begin
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC=1

[env:rpipico2w]
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyACM0
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
board_build.core = earlephilhower
lib_ldf_mode = chain+
#enable serial.begin
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC=1


[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560

[env:teensy41]
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    PaulStoffregen/Time
    micro_ros_arduino
    https://github.com/micro-ROS/micro_ros_arduino.git
build_flags =
    -D ARDUINO_ARCH_TEENSY

[env:teensy40] 
board = teensy40

[env:teensy36]
board = teensy36

[env:teensy35]
board = teensy35

[env:teensy31] 
board = teensy31

[env:dev] 
board = teensy40
build_flags = 
    -I ../config
    -D USE_DEV_CONFIG

[env:vattenkar] 
board = teensy40
build_flags = 
    -I ../config
    -D USE_VATTENKAR_CONFIG
