ekf_localization:
  ros__parameters:
    frequency: 20.0  # Lowering frequency as a test
    sensor_timeout: 0.5  # Increasing timeout for sensor data
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link

    imu0: /rover/imu
    imu0_config: [false, false, false,
                  true, true, true,
                  true, true, true]
    imu0_differential: false
    imu0_queue_size: 10

    gps0: /rover/gps
    gps0_config: [true, true, false,
                  false, false, false,
                  false, false, false]
    gps0_differential: false
    gps0_queue_size: 10

    imu0_pose_rejection_threshold: 0.8
    imu0_twist_rejection_threshold: 0.8
    gps0_rejection_threshold: 5.0

    publish_tf: true
    world_frame: map
    publish_diagnostics: true  # Enable diagnostics
