// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quaternion } from "./Quaternion";
import type { Vector3 } from "./Vector3";

export type IMU = { orientation_covariance: Quaternion, angular_velocity_covariance: Vector3, linear_acceleration_covariance: Vector3, };
