// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMU } from "./IMU";
import type { Twist } from "./Twist";
import type { Vector3 } from "./Vector3";

export type Message = { "type": "Twist" } & Twist | { "type": "IMU" } & IMU | { "type": "GPS" } & Vector3;
