// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vector3 } from "./Vector3";

export type Twist = { linear: Vector3, angular: Vector3, };
