[package]
name = "fake-rover"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "=2.0.0-rc.3" }
ctrlc = "3.4.5"
prost = "0.13.4"
prost-stream = { version = "0.1.2", features = ["async"] }
rand = "0.8.5"
rover-msgs = { path = "../rover-msgs" }
