<?xml version='1.0'?>

<robot name="aruco_marker" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="robot_name" value="aruco_marker" />
	<xacro:property name="pole_mass" value="0"/>
	<xacro:property name="pole_height" value="1"/>
	<xacro:property name="pole_radius" value=".015"/>
	<xacro:property name="marker_mass" value=".240"/>
	<xacro:arg name="model_file" default="4X4_50-5.dae"/>
	<!-- <xacro:arg name="file_path" default=""/> -->

	<!-- Make Chassis of Bot -->
	<link name="basePole">
		<pose>0 0 0.1 0 0 0</pose>

		<inertial>
			<mass value="${pole_mass}"/>
      		<origin xyz="0 0 0" rpy=" 0 0 0"/>

      		<inertia 
      			ixx="0" ixy="0" ixz="0"
      			iyy="0" iyz="0"
      			izz="0"
      		/>
		</inertial>

		<collision name="collision">
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<box size="${2 * pole_radius} ${2 * pole_radius} ${pole_height}"/>
			</geometry>
		</collision>

		<visual name="pole_visual">
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<cylinder radius="${pole_radius}" length="${pole_height}"/>
			</geometry>

		</visual>

	</link>

	<!-- Aruco Marker -->
	<link name="arucoMarker">
		<inertial>
			<mass value="${marker_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>

			<inertia
		        ixx="1e-6" ixy="0.0" ixz="0.0"
		        iyy="1e-6" iyz="0.0"
		        izz="1e-6"
		      />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="file://$(find sim_package)/models/4x4_50-5/$(arg model_file)"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.2 0.2 0.2"/>
			</geometry>
		</collision>
	</link>

	<!-- Project center to the ground -->
	<link name="world"></link>

	<joint name="world_joint" type="fixed">
		<origin xyz="0 0 ${0.5 * pole_height}" rpy="0 0 0" />
		<parent link="world"/>
		<child link="basePole" />
	</joint>

	<joint name="marker_pole_joint" type="fixed">
		<origin xyz="0 0 ${0.5 * pole_height + 0.1}" rpy="0 0 0" />

		<parent link="basePole"/>
		<child link="arucoMarker" />
	</joint>

	<!-- Color of stuff -->
	<gazebo reference="basePole">
		<material>Gazebo/White</material>
		<kp>1000000.0</kp> <!-- kp and kd for rubber -->
		<kd>100.0</kd>
		<mu1>1.0</mu1>
		<mu2>1.0</mu2>
		<maxVel>1.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>

</robot>