
- ros_topic_name: "/rover/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/rover/imu"
  gz_topic_name: "/world/world1/model/rover/link/imu_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"  
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/rover/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/camera_front/camera_info"
  gz_topic_name: "/world/world1/model/rover/link/camera_link/sensor/camera_front/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/depth/image_rect_raw"
  gz_topic_name: "/world/world1/model/rover/link/camera_link/sensor/camera_front/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/color/image_raw"
  gz_topic_name: "/world/world1/model/rover/link/camera_link/sensor/camera_front/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/depth/points"
  gz_topic_name: "/world/world1/model/rover/link/camera_link/sensor/camera_front/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
- ros_topic_name: "/rover/gps"
  gz_topic_name: "/world/world1/model/rover/link/gps_link/sensor/gps/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS




