# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msgs.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmsgs.proto\x12\x05rover\"s\n\x07Message\x12\x1d\n\x03imu\x18\x01 \x01(\x0b\x32\x0e.rover.IMUDataH\x00\x12\x1d\n\x03gps\x18\x02 \x01(\x0b\x32\x0e.rover.GPSDataH\x00\x12\x1d\n\x05twist\x18\x03 \x01(\x0b\x32\x0c.rover.TwistH\x00\x42\x0b\n\tdata_type\"H\n\x05Twist\x12\x1e\n\x06linear\x18\x01 \x01(\x0b\x32\x0e.rover.Vector3\x12\x1f\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x0e.rover.Vector3\"\xed\x01\n\x07GPSData\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x14\n\x0cground_speed\x18\x04 \x01(\x02\x12\x12\n\nsatellites\x18\x05 \x01(\r\x12\x16\n\x0emode_indicator\x18\x06 \x01(\r\x12\x12\n\nseparation\x18\x07 \x01(\x02\x12\x13\n\x0btrue_course\x18\x08 \x01(\x02\x12\x1c\n\x14true_course_magnetic\x18\t \x01(\x02\x12\x10\n\x08\x64ilution\x18\n \x01(\x02\x12\x10\n\x08utc_time\x18\x0b \x01(\r\"\x94\x02\n\x07IMUData\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.rover.Header\x12&\n\x0borientation\x18\x02 \x01(\x0b\x32\x11.rover.Quaternion\x12\x1e\n\x16orientation_covariance\x18\x03 \x03(\x01\x12(\n\x10\x61ngular_velocity\x18\x04 \x01(\x0b\x32\x0e.rover.Vector3\x12#\n\x1b\x61ngular_velocity_covariance\x18\x05 \x03(\x01\x12+\n\x13linear_acceleration\x18\x06 \x01(\x0b\x32\x0e.rover.Vector3\x12&\n\x1elinear_acceleration_covariance\x18\x07 \x03(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"6\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\r\n\x05stamp\x18\x02 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\tB\x16Z\x14rover-msgs/go/msgspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024rover-msgs/go/msgspb'
  _globals['_MESSAGE']._serialized_start=21
  _globals['_MESSAGE']._serialized_end=136
  _globals['_TWIST']._serialized_start=138
  _globals['_TWIST']._serialized_end=210
  _globals['_GPSDATA']._serialized_start=213
  _globals['_GPSDATA']._serialized_end=450
  _globals['_IMUDATA']._serialized_start=453
  _globals['_IMUDATA']._serialized_end=729
  _globals['_QUATERNION']._serialized_start=731
  _globals['_QUATERNION']._serialized_end=787
  _globals['_VECTOR3']._serialized_start=789
  _globals['_VECTOR3']._serialized_end=831
  _globals['_HEADER']._serialized_start=833
  _globals['_HEADER']._serialized_end=887
# @@protoc_insertion_point(module_scope)
